"""add cover colour

Revision ID: 86febe669fd4
Revises: c7467954c508
Create Date: 2026-08-12 12:56:31.666700

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "86febe669fd4"
down_revision: str | None = "c7467954c508"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("cover_color", sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "cover_color")
    # ### end Alembic commands ###
