"""add search cache

Revision ID: babada2ed372
Revises: 50564141f59d
Create Date: 2026-08-10 18:25:08.007576

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "babada2ed372"
down_revision: str | None = "50564141f59d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_searches",
        sa.Column("query_key", sa.String(length=512), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("query_key"),
    )
    op.create_index(
        op.f("ix_cached_searches_fetched_at"), "cached_searches", ["fetched_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cached_searches_fetched_at"), table_name="cached_searches")
    op.drop_table("cached_searches")
    # ### end Alembic commands ###
