"""identify authors by provider id

Revision ID: c7467954c508
Revises: ffabfc7af9dd
Create Date: 2026-08-11 16:59:35.613751

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c7467954c508"
down_revision: str | None = "ffabfc7af9dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authors", sa.Column("hardcover_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_authors_hardcover_id"), "authors", ["hardcover_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_authors_hardcover_id"), table_name="authors")
    op.drop_column("authors", "hardcover_id")
    # ### end Alembic commands ###
