"""generalize provider cache

Revision ID: ffabfc7af9dd
Revises: babada2ed372
Create Date: 2026-08-11 16:22:43.843848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ffabfc7af9dd"
down_revision: str | None = "babada2ed372"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Dropped and recreated rather than renamed with a back-filled `kind`.
    # Discarding a cache is free: the rows expire within the TTL anyway, and the
    # only cost of an empty cache is one extra upstream call per query.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_provider_responses",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("cache_key", sa.String(length=512), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("kind", "cache_key"),
    )
    op.create_index(
        op.f("ix_cached_provider_responses_fetched_at"),
        "cached_provider_responses",
        ["fetched_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_cached_searches_fetched_at"), table_name="cached_searches")
    op.drop_table("cached_searches")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_searches",
        sa.Column("query_key", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.Column(
            "fetched_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("query_key", name=op.f("cached_searches_pkey")),
    )
    op.create_index(
        op.f("ix_cached_searches_fetched_at"), "cached_searches", ["fetched_at"], unique=False
    )
    op.drop_index(
        op.f("ix_cached_provider_responses_fetched_at"), table_name="cached_provider_responses"
    )
    op.drop_table("cached_provider_responses")
    # ### end Alembic commands ###
